* test
** проверить что фреймы показа таймлайна перезагружаются
* layout
** otsourcing-orgy growing - показывать оверлеем чтобы был возможность ее растянуть.
*** вообще это изза того что add class не реализован
* js
** эрозии цепляются к уже эродированным элементам. это когда не используется дипест.
** эрозии цепляются к элементам, которые не видимы. типа скрипт или что-то похожее
** реализовать addclass
** реализовать removeClass
** реализовать addText
* elm
** показ ассамбляжа
*** варик разбить таймлайн на эвенты иууид привязывать к разбитому на части таймлайну. все запускать через отложенные таски.
**** рассчитать время откладывания
***** перемешиваем эвенты
***** сначала считаем дурейшен у всех тасков. в том числе и ассамбляжей
***** потом рассчитываем смещения от начала
***** потом флэтим массив массивов эвентов которые получается из обычных эвентов и ассамбляжей
***** потом собираем пучек команд
***** в конец добавляем команду, которая перезапускает процесс показывания. вновь перемешивает таймлайн
***
